### ISSUE TITLE
u3d_demo crashes

### ISSUE THREAD

**Issue by apnadkarni** [nico-robert/haru#2]
The u3d_demo crashes because the function `HPDF_Page_Create3DAnnot ` is defined in the CFFI using the libhpdf 2.4 prototype but the package expects 2.3.0 as far as I know. This function has [changed ](https://github.com/libharu/libharu/commit/ac6052c588e7a6ade5d65c4a29d1a810b6c0e848?diff=unified#diff-8fb8e53db24a06b96e4138e4585bce2244fbf72fd46e6627c1ba4ceb7c6916c2L457) between 2.3 and 2.4.

Patch forthcoming...

**Comment by nico-robert** [comment]
Error on my part, all examples have been tested with libharu 2.3 except for this example, thanks for the correction.
